"""Add duration field to Video model

Revision ID: 473337d41e02
Revises: e71993fd6f44
Create Date: 2024-05-17 07:56:02.467649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473337d41e02'
down_revision = 'e71993fd6f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
