"""Remove description column from video table

Revision ID: e71993fd6f44
Revises: e39391531ae2
Create Date: 2024-05-10 09:19:08.560158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71993fd6f44'
down_revision = 'e39391531ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
